# Generated by Django 5.1.7 on 2025-03-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField(max_length=10)),
                ('account_type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=64)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
    ]
