# Generated by Django 5.1.7 on 2025-03-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='account_number',
            field=models.BigIntegerField(),
        ),
    ]
